# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import item_pb2 as item__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in item_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ItemServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckItemAvailability = channel.unary_unary(
                '/ItemService/CheckItemAvailability',
                request_serializer=item__pb2.ItemRequest.SerializeToString,
                response_deserializer=item__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.SubmitClaim = channel.unary_unary(
                '/ItemService/SubmitClaim',
                request_serializer=item__pb2.ClaimRequest.SerializeToString,
                response_deserializer=item__pb2.ClaimResponse.FromString,
                _registered_method=True)


class ItemServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckItemAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckItemAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckItemAvailability,
                    request_deserializer=item__pb2.ItemRequest.FromString,
                    response_serializer=item__pb2.ItemResponse.SerializeToString,
            ),
            'SubmitClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitClaim,
                    request_deserializer=item__pb2.ClaimRequest.FromString,
                    response_serializer=item__pb2.ClaimResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ItemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckItemAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/CheckItemAvailability',
            item__pb2.ItemRequest.SerializeToString,
            item__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ItemService/SubmitClaim',
            item__pb2.ClaimRequest.SerializeToString,
            item__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """Peer-to-peer mutual exclusion service.
    Every node runs this server AND calls it on its peers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/MutexService/RequestAccess',
                request_serializer=item__pb2.AccessRequest.SerializeToString,
                response_deserializer=item__pb2.AccessReply.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """Peer-to-peer mutual exclusion service.
    Every node runs this server AND calls it on its peers.
    """

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=item__pb2.AccessRequest.FromString,
                    response_serializer=item__pb2.AccessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """Peer-to-peer mutual exclusion service.
    Every node runs this server AND calls it on its peers.
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MutexService/RequestAccess',
            item__pb2.AccessRequest.SerializeToString,
            item__pb2.AccessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
