# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: item.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\"5\n\x0bItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x15\n\rlamport_clock\x18\x02 \x01(\x05\"I\n\x0cItemResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rlamport_clock\x18\x03 \x01(\x05\"J\n\x0c\x43laimRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x15\n\rlamport_clock\x18\x03 \x01(\x05\"H\n\rClaimResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rlamport_clock\x18\x03 \x01(\x05\"3\n\rAccessRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\"1\n\x0b\x41\x63\x63\x65ssReply\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x32u\n\x0bItemService\x12\x36\n\x15\x43heckItemAvailability\x12\x0c.ItemRequest\x1a\r.ItemResponse\"\x00\x12.\n\x0bSubmitClaim\x12\r.ClaimRequest\x1a\x0e.ClaimResponse\"\x00\x32=\n\x0cMutexService\x12-\n\rRequestAccess\x12\x0e.AccessRequest\x1a\x0c.AccessReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=14
  _globals['_ITEMREQUEST']._serialized_end=67
  _globals['_ITEMRESPONSE']._serialized_start=69
  _globals['_ITEMRESPONSE']._serialized_end=142
  _globals['_CLAIMREQUEST']._serialized_start=144
  _globals['_CLAIMREQUEST']._serialized_end=218
  _globals['_CLAIMRESPONSE']._serialized_start=220
  _globals['_CLAIMRESPONSE']._serialized_end=292
  _globals['_ACCESSREQUEST']._serialized_start=294
  _globals['_ACCESSREQUEST']._serialized_end=345
  _globals['_ACCESSREPLY']._serialized_start=347
  _globals['_ACCESSREPLY']._serialized_end=396
  _globals['_ITEMSERVICE']._serialized_start=398
  _globals['_ITEMSERVICE']._serialized_end=515
  _globals['_MUTEXSERVICE']._serialized_start=517
  _globals['_MUTEXSERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
